api_pomodoro_start:
    path:       /api/pomodoro/start
    controller: App\Controller\Pomodoro\StartPomodoroController
    methods:    [POST]

api_pomodoro_finish:
    path:       /api/pomodoro/{id}/finish
    controller: App\Controller\Pomodoro\FinishPomodoroController
    methods:    [PATCH]

api_pomodoro_history:
    path:       /api/pomodoro/history
    controller: App\Controller\Pomodoro\HistoryPomodoroController
    methods:    [GET]

api_pomodoro_stats:
    path:       /api/pomodoro/stats
    controller: App\Controller\Pomodoro\StatsPomodoroController
    methods:    [GET]
